name: WMS
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # numberpicker: ^2.1.0
  # flutter_number_picker: ^1.0.0
  # flutter_spinbox: ^1.0.0
  # font_awesome_flutter: ^10.4.0
  font_awesome_flutter: ^10.2.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  bs_flutter: any
  bs_flutter_card: ^1.0.0
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/  #เรียกใช้ Folder รูป
